-- MySQL Script generated by MySQL Workbench
-- Tue Mar  3 08:18:17 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CRM_GR4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CRM_GR4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CRM_GR4` DEFAULT CHARACTER SET utf8 ;
USE `CRM_GR4` ;

-- -----------------------------------------------------
-- Table `CRM_GR4`.`Ansatte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM_GR4`.`Ansatte` (
  `ansatt_id` INT NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(50) NULL,
  `etter_navn` VARCHAR(50) NULL,
  `telefonnummer` VARCHAR(30) NULL,
  `e-post/mail` VARCHAR(100) NULL,
  `rolle` VARCHAR(50) NULL,
  PRIMARY KEY (`ansatt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM_GR4`.`Kunder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM_GR4`.`Kunder` (
  `kunde_id` INT NOT NULL AUTO_INCREMENT,
  `bedrift_navn` VARCHAR(100) NULL,
  `telefonnummer` VARCHAR(30) NULL,
  `e-post/mail` VARCHAR(100) NULL,
  `adresse` VARCHAR(100) NULL,
  `postnummer` VARCHAR(10) NULL,
  `by` VARCHAR(50) NULL,
  PRIMARY KEY (`kunde_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM_GR4`.`Ansatt_Kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM_GR4`.`Ansatt_Kunde` (
  `Ansatte_ansatt_id` INT NOT NULL,
  `Kunder_kunde_id` INT NOT NULL,
  `rolle` VARCHAR(50) NULL,
  `start_dato` DATE NULL,
  `slutt_dato` DATE NULL,
  PRIMARY KEY (`Ansatte_ansatt_id`, `Kunder_kunde_id`),
  INDEX `fk_Ansatt_Kunde_Kunder1_idx` (`Kunder_kunde_id` ASC),
  CONSTRAINT `fk_Ansatt_Kunde_Ansatte1`
    FOREIGN KEY (`Ansatte_ansatt_id`)
    REFERENCES `CRM_GR4`.`Ansatte` (`ansatt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ansatt_Kunde_Kunder1`
    FOREIGN KEY (`Kunder_kunde_id`)
    REFERENCES `CRM_GR4`.`Kunder` (`kunde_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CRM_GR4`.`Kontaktperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CRM_GR4`.`Kontaktperson` (
  `kontakt_id` INT NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(50) NULL,
  `etternavn` VARCHAR(50) NULL,
  `stilling` VARCHAR(60) NULL,
  `telefonnummer` VARCHAR(30) NULL,
  `e-post/mail` VARCHAR(100) NULL,
  `kunde_id` INT NOT NULL,
  PRIMARY KEY (`kontakt_id`, `kunde_id`),
  INDEX `fk_Kontaktperson_Kunder_idx` (`kunde_id` ASC),
  CONSTRAINT `fk_Kontaktperson_Kunder`
    FOREIGN KEY (`kunde_id`)
    REFERENCES `CRM_GR4`.`Kunder` (`kunde_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
